validate environment variables with zod
add environment variable validation with zod. this
will help ensure that you have all required env
variables before starting the app as well as being
very clear why the app failed to start.

example error message:
```
❌ Invalid environment variables: { SECRET: [ 'Required' ] }
Error: Invalid environment variables

```